#端口配置
server:
  port: 8082

#数据库，redis相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.29.230:33060/smallrouting?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 118.89.29.230
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 50
        max-wait: 1s
    password: 123456
  thymeleaf:
    cache: false

#短信相关配置
msg:
  app:
    id: 1400132050
    key: 93aaf154b1044701eb395ca253555a4a
  template:
    id: 183106
  timeout: 10

photo:
  app:
    id: AKIDLSJuEOG1TjnbAUeZEdppb9TnshGb7X7R
    key: IK6cvylIZgX8UdXBZhfOr56sOfhZCZkj
  save:
    path: /home/yrs/photo/

#配置日志
logging:
  config: classpath:log4j2.yml

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml






